modLoader = "javafml"
loaderVersion = "[37,)"
issueTrackerURL = "https://github.com/ImUrX/screencopy/issues"
license = "MIT OR Apache-2.0"

[[mods]]
modId = "screencopy"
version = "${version}"
displayName = "Screencopy"
displayURL = "https://github.com/ImUrX/screencopy"
credits = "Thanks KiboTheCookie for the icon design."
authors = "ImUrX"
description = '''
Let's you save screenshots to your clipboard
'''
logoFile = "icon.png"

[[dependencies.screencopy]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.screencopy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.screencopy]]
modId = "cloth_config"
mandatory = true
versionRange = "[5.3.58,)"
ordering = "NONE"
side = "CLIENT"
