modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/ImUrX/screencopy/issues"
license = "MIT OR Apache 2.0"

[[mods]]
modId = "screencopy"
version = "${version}"
displayName = "Screencopy"
authors = "ImUrX"
description = '''
Let's you save screenshots to your clipboard
'''
#logoFile = ""

[[dependencies.screencopy]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.screencopy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.screencopy]]
modId = "cloth_config"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "CLIENT"
