plugins {
    id 'com.gradleup.shadow'
}

architectury {
    common rootProject.enabled_platforms.split(",")
}

configurations {
    shadowCommon
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    // Remove the next line if you don't want to depend on the API
    //modApi "dev.architectury:architectury:${rootProject.architectury_version}"
    api("me.shedaniel.cloth:cloth-config:${rootProject.cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }
}

jar {
    archiveClassifier = "raw"
}

java {
    withSourcesJar()
}

shadowJar {
    dependsOn(jar)
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    from rootProject.file("LICENSE.md")
}

configurations {
    apiElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
    runtimeElements {
        outgoing.artifacts.clear()
        outgoing.artifact(shadowJar)
    }
}

//publishing {
//    publications {
//        mavenCommon(MavenPublication) {
//            artifactId = rootProject.archives_base_name
//            from components.java
//        }
//    }
//
//    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
//    repositories {
//        // Add repositories to publish to here.
//    }
//}
