modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/ImUrX/screencopy/issues"
license = "MIT OR Apache-2.0"

[[mods]]
modId = "screencopy"
version = "${version}"
displayName = "Screencopy"
displayURL = "https://github.com/ImUrX/screencopy"
credits = "Thanks KiboTheCookie for the icon design."
authors = "ImUrX"
logoFile = "icon.png"
updateJSONURL = "https://api.modrinth.com/updates/screencopy/forge_updates.json?neoforge=only"

[[dependencies.screencopy]]
modId = "neoforge"
type = "required"
versionRange = "[21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.screencopy]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.screencopy]]
modId = "cloth_config"
mandatory = true
versionRange = "[16.0.141,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "screencopy.common.mixins.json"
